--- #YAML:1.0
name:               Term-Pager
version:            1.01
abstract:           Page through text, a screenful at a time, like more or less
author:
    - Jeff Weisberg <http://www.tcp4me.com/>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Term::Cap:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
